/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmapTransformer;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.Buffer;

public class App {

    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Bitmap b = new Bitmap("./assets/input.bmp", "./assets/", "output.bmp" );
        b.getBitmap();
        b.writeToFile();

    }
}
